version: 0.2

phases:
  pre_build:
    commands:
      - cd terraform-root
      - terraform init -input=false

  build:
    commands:
      - terraform validate
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan
